# Generated by Django 3.2.5 on 2021-07-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='names',
        ),
    ]
